/* Data that will be obtain by call to backend
* */

import * as temp_photos from "./temp_photos"

/*Initial checklist list*/
const checklist_trees = [
  {
    checklist_id: 0,
    id: -1,
    num_values:[],
    values:[
      {
        id: 1,
        name: "Intubation Difficile ? ",
        section_title : "Vérifications concernant l'intubation difficile",
        cond: {"yes":[], "no":[], num:[]},
        check : ["yes","no","idk"],
        color : [0,1,2],
        pre_check : {if:[{var:"difficult_intubation",op:"est",val:"vrai"}],then:"yes"},
        values: [
          {
            id: 2,
            name: "A confirmer l'incubation difficile",
            cond: {"yes":[], "no": [], "idk" : [1], num:[]},
            check : ["yes","no"],
            color : [1,0],
            values: []
          },
          {
            id: 3,
            name: "2ème Anesthésiste",
            cond: {"yes":[1], "no":[], num:[]},
            check : ["yes","no"],
            color : [1,0],
            values: []
          },
          {
            id: 4,
            name: "2ème Infirmière",
            cond: {"yes":[1], "no":[], num:[]},
            check : ["yes","no"],
            color : [0,1],
            values: []
          },
          {
            id: 5,
            name: "Matériel",
            cond: {"yes":[1], "no":[], num:[]},
            check : [],
            values: [
              {
                id: 6,
                name: "Glidescope",
                cond: {"yes":[1], "no":[], num:[]},
                check : ["yes","no"],
                color : [0,1],
                values: []
              },
              {
                id: 7,
                name: "Laryngoscope",
                cond: {"yes":[1], "no":[], num:[]},
                check : ["yes","no"],
                color : [0,1],
                values: []
              },
              {
                id: 8,
                name: "Set Trachéo",
                cond: {"yes":[1], "no":[], num:[]},
                check : ["yes","no"],
                color : [0,1],
                values: []
              },
            ]
          },
          {
            id: 9,
            name: "Protocole",
            cond: {"yes":[1], "no":[], num:[]},
            check : ["yes","no"],
            color : [0,1],
            values: []
          },
        ]
      },
      {
        id: 10,
        name: "Est-elle susceptible d'être enceinte ?",
        section_title : "Vérifications concernant une possible grossesse",
        comment: "(Les données patient nous indiquent que la patiente est âgée entre 15 et 60 ans)",
        cond: {"yes":[], "no":[], num:[{var:"age",op:">",val:15},{var:"age",op:"<",val:60}, {var:"gender",op:"=",val:"F"}]},
        check : ["yes","no"],
        color : [0,1],
        values: [
          {
            id: 11,
            name: "Arrêt des rêgles depuis ?",
            cond: {"yes":[10], "no":[], num:[]},
            check : ["text"],
            values: []
          },
          {
            id: 12,
            name: "Test disponible ?",
            cond: {"yes":[10], "no":[], num:[]},
            check : ["yes","no"],
            color : [0,1],
            values: [
              {
                id: 13,
                name: "Négatif ?",
                cond: {"yes":[12], "no":[], num:[]},
                check : ["yes", "no"],
                color : [0,1],
                values: []
              },
              {
                id: 14,
                name: "Faire test maintenant ?",
                cond: {"yes":[], "no":[12], num:[]},
                check : ["yes", "no"],
                color : [0,1],
                values: []
              },
              {
                id: 15,
                name: "Postposer l'intervention ?",
                cond: {"yes":[], "no":[12], num:[]},
                check : ["yes", "no"],
                color : [0,1],
                values: []
              },
            ]
          },
        ]
      },
      {
        id: 16,
        name: "Le patient est-il diabétique ?",
        section_title : "Vérification concernant le diabète",
        cond: {"yes":[], "no":[], num:[]},
        check : ["yes","no"],
        color : [0,1],
        pre_check : {if:[{var:"diabetic",op:"est",val:"vrai"}],then:"yes"},
        values: [
          {
            id: 17,
            name: "Traitement Oral ?",
            cond: {"yes":[16], "no":[], num:[]},
            check : ["yes", "no"],
            color : [0,1],
            values: [
              {
                id: 18,
                name: "Arrêt des médicaments ?",
                cond: {"yes":[17], "no":[], num:[]},
                check : ["yes", "no"],
                color : [0,1],
                values: []
              },
            ]
          },
          {
            id: 19,
            name: "Traitement par piqure à insuline ?",
            cond: {"yes":[16], "no":[17], num:[]},
            check : ["yes", "no"],
            color : [0,1],
            values: [
              {
                id: 20,
                name: "Dernière piqure le ? ",
                cond : {"yes":[19], "no":[], num:[]},
                check: ["text"],
                values: []
              }
            ]
          },
          {
            id: 21,
            name: "Glycémie à l'arrivée HJ ?",
            cond: {"yes":[16], "no":[], num:[]},
            check : ["normal", "anormal"],
            color : [0,1],
            values: []
          },
        ]
      },
      {
        id: 22,
        name: "Consentement chirugicaux et anéstésiques de père/mère",
        section_title : "Concernant les consentements parentaux",
        comment: "Enfant de <15 ans, nécessite les consentement des parents",
        cond: {"yes":[],"no":[],num:[{var:"age",op:"<",val:15}]},
        check: [],
        values: [
          {
            id: 23,
            name: "Consentement chirugical du père",
            cond: {"yes":[], num:[{var:"age",op:"<",val:15}]},
            check: ["yes", "no"],
            color : [0,1],
            values: []
          },
          {
            id: 24,
            name: "Consentement chirurgical de la mère",
            cond: {"yes":[], num:[{var:"age",op:"<",val:15}]},
            check: ["yes", "no"],
            color : [0,1],
            values: []
          },
          {
            id: 25,
            name: "Consentement anestésique du père",
            cond: {"yes":[], num:[{var:"age",op:"<",val:15}]},
            check: ["yes", "no"],
            color : [0,1],
            values: []
          },
          {
            id: 26,
            name: "Consentement anestésique de la mère",
            cond: {"yes":[], num:[{var:"age",op:"<",val:15}]},
            check: ["yes", "no"],
            color : [0,1],
            values: []
          },
        ]
      },
      {
        id: 27,
        name: "Checks vernis à ongle",
        section_title : "Checks généraux pour anestésie",
        comment: "Ado/Adulte, nécessite vérification du vernis à ongle et des prothèses auditives/dentaires",
        cond: {"yes":[], num:[{var:"age",op:">",val:10}]},
        check: ["ok", "not_ok"],
        color : [0,1],
        values: [
          {
            id: 28,
            name: "Check Prothèses dentaires",
            cond: {"yes":[], num:[{var:"age",op:">",val:10}]},
            check: ["ok", "not_ok"],
            color : [0,1],
            values: []
          },
          {
            id: 29,
            name: "Check Prothèses auditives",
            cond: {"yes":[], num:[{var:"age",op:">",val:10}]},
            check: ["ok", "not_ok"],
            color : [0,1],
            values: []
          },
        ]
      },
      {
        id: 30,
        name: "Maladie transmissible ?",
        section_title : "Vérifications maladadies transmissibles",
        comment : "Si oui, l'information sera considérée dans les checklists suivantes (accueil du bloc, salle de réveil)",
        cond: {"yes":[], num:[]},
        check: ["yes", "no"],
        color : [0,1],
        values: [
          {
            id: 31,
            name: "Par voie aérienne ? ",
            cond: {"yes":[30], num:[]},
            check: ["yes", "no"],
            color : [0,1],
            values: [
              {
                id: 32,
                name : "EPI (Masque FFP2, Visière)",
                cond : {"yes":[31], num:[]},
                check: ["yes", "no"],
                color : [0,1],
                values: []
              },
              {
                id: 33,
                name : "Protocole",
                cond : {"yes":[31], num:[]},
                check: ["ok", "not_ok"],
                color : [0,1],
                values: []
              }
            ]
          },
          {
            id: 34,
            name: "Par voie sanguine ? ",
            cond: {"yes":[30], "no":[31], num:[]},
            check: ["yes", "no"],
            color : [0,1],
            values: [
              {
                id: 35,
                name : "EPI (Gants, blouses, lunettes)",
                cond : {"yes":[34], num:[]},
                check: ["yes", "no"],
                color : [0,1],
                values: []
              },
              {
                id: 36,
                name : "Protocole",
                cond : {"yes":[34], num:[]},
                check: ["ok", "not_ok"],
                color : [0,1],
                values: []
              }
            ]
          },
          {
            id: 37,
            name: "Par contact ? ",
            cond: {"yes":[30], "no":[31,34], num:[]},
            check: ["yes", "no"],
            color : [0,1],
            values: [
              {
                id: 38,
                name : "EPI",
                cond : {"yes":[37], num:[]},
                check: ["yes", "no"],
                color : [0,1],
                values: []
              },
              {
                id: 39,
                name : "Protocole",
                cond : {"yes":[37], num:[]},
                check: ["ok", "not_ok"],
                color : [0,1],
                values: []
              }
            ]
          },
        ]
      }
    ]
  },
  {
    checklist_id: 1,
    id: -1,
    num_values:[],
    values:[
      {
        id: 1,
        name: "Intubation ? ",
        cond: {"yes": [], "no": [], num: []},
        check: ["yes", "no", "?"],
        color: [0,1,2],
        pre_check: {if: [{var: "difficult_intubation", op: "est", val: "vrai"}], then: "yes"},
        values: []
      },
      {
        id: 2,
        name: "Test ? ",
        cond: {"yes": [], "no": [], num: []},
        check: ["yes", "no", "?"],
        color: [0,1,2],
        values: []
      }
    ]
  }
];

const checklist_arrays = [
  // [
  //   [
  //     '"id"',
  //     '"name"',
  //     '"parent_id"',
  //     '"position"',
  //     '"comment"',
  //     '"section_title"',
  //     '"cond"',
  //     '"check"',
  //     '"color"',
  //     '"pre_check"',
  //     '"importance'
  //   ],
  //   [
  //     1,
  //     '"Intubation Difficile ? "',
  //     -1,
  //     0,
  //     null,
  //     '"Vérifications concernant l\'intubation difficile"',
  //     '{"yes":[],"no":[],"num":[]}',
  //     '["yes","no","idk"]',
  //     '[0,1,2]',
  //     '{"if":[[{"var":"difficult_intubation","op":"est","val":"vrai"}]],"then":"yes"}',
  //     0,
  //   ],
  //   [
  //     2,
  //     '"A confirmer l\'incubation difficile"',
  //     1,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[],"no":[],"idk":[1],"num":[]}',
  //     '["yes","no"]',
  //     '[1,0]',
  //     null,
  //     0,
  //   ],
  //   [
  //     3,
  //     '"2ème Anesthésiste"',
  //     1,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[1,0]',
  //     null,
  //     0,
  //   ],
  //   [
  //     4,
  //     '"2ème Infirmière"',
  //     1,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     5,
  //     '"Matériel"',
  //     1,
  //     3,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '[]',
  //     null,
  //     null,
  //     0,
  //   ],
  //   [
  //     6,
  //     '"Glidescope"',
  //     5,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     7,
  //     '"Laryngoscope"',
  //     5,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     8,
  //     '"Set Trachéo"',
  //     5,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     9,
  //     '"Protocole"',
  //     1,
  //     4,
  //     null,
  //     null,
  //     '{"yes":[1],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     10,
  //     '"Est-elle susceptible d\'être enceinte ?"',
  //     -1,
  //     1,
  //     '"(Les données patient nous indiquent que la patiente est âgée entre 15 et 60 ans)"',
  //     '"Vérifications concernant une possible grossesse"',
  //     '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":15},{"var":"age","op":"<","val":60},{"var":"gender","op":"=","val":"F"}]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     11,
  //     '"Arrêt des rêgles depuis ?"',
  //     10,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[10],"no":[],"num":[]}',
  //     '["text"]',
  //     null,
  //     null,
  //     0,
  //   ],
  //   [
  //     12,
  //     '"Test disponible ?"',
  //     10,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[10],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     13,
  //     '"Négatif ?"',
  //     12,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[12],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     14,
  //     '"Faire test maintenant ?"',
  //     12,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[],"no":[12],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     15,
  //     '"Postposer l\'intervention ?"',
  //     12,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[],"no":[12],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     16,
  //     '"Le patient est-il diabétique ?"',
  //     -1,
  //     2,
  //     null,
  //     '"Vérifications concernant le diabète"',
  //     '{"yes":[],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     '{"if":[[{"var":"diabetic","op":"est","val":"vrai"}]],"then":"yes"}',
  //     0,
  //   ],
  //   [
  //     17,
  //     '"Traitement Oral ?"',
  //     16,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[16],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     18,
  //     '"Arrêt des médicaments ?"',
  //     17,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[17],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     19,
  //     '"Traitement par piqure à insuline ?"',
  //     16,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[16],"no":[17],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     20,
  //     '"Dernière piqure le ? "',
  //     19,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[19],"no":[],"num":[]}',
  //     '["text"]',
  //     null,
  //     null,
  //     0,
  //   ],
  //   [
  //     21,
  //     '"Glycémie à l\'arrivée HJ ?"',
  //     16,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[16],"no":[],"num":[]}',
  //     '["normal","anormal"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     22,
  //     '"Consentement chirugicaux et anéstésiques de père/mère"',
  //     -1,
  //     3,
  //     '"Enfant de <15 ans, nécessite les consentement des parents"',
  //     '"Vérifications concernant les consentements"',
  //     '{"yes":[],"no":[],"num":[{"var":"age","op":"<","val":15}]}',
  //     '[]',
  //     null,
  //     null,
  //     0,
  //   ],
  //   [
  //     23,
  //     '"Consentement chirugical du père"',
  //     22,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":"<","val":15}]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     24,
  //     '"Consentement chirurgical de la mère"',
  //     22,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":"<","val":15}]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     25,
  //     '"Consentement anestésique du père"',
  //     22,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":"<","val":15}]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     26,
  //     '"Consentement anestésique de la mère"',
  //     22,
  //     3,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":"<","val":15}]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     27,
  //     '"Checks vernis à ongle"',
  //     -1,
  //     4,
  //     '"Ado/Adulte, nécessite vérification du vernis à ongle et des prothèses auditives/dentaires"',
  //     '"Checks généraux pour anestésie"',
  //     '{"yes":[],"num":[{"var":"age","op":">","val":10}]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     28,
  //     '"Check Prothèses dentaires"',
  //     27,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":">","val":10}]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     29,
  //     '"Check Prothèses auditives"',
  //     27,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[],"num":[{"var":"age","op":">","val":10}]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     30,
  //     '"Maladie transmissible ?"',
  //     -1,
  //     5,
  //     '"Si oui, l\'information sera considérée dans les checklists suivantes (accueil du bloc, salle de réveil)"',
  //     '"Vérifications maladadies transmissibles"',
  //     '{"yes":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     31,
  //     '"Par voie aérienne ? "',
  //     30,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[30],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     '{"if":[[{"val":"yes","var":34},{"val":"yes","var":37}]],"then":"no"}',
  //     0,
  //   ],
  //   [
  //     32,
  //     '"EPI (Masque FFP2, Visière)"',
  //     31,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[31],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     33,
  //     '"Protocole"',
  //     31,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[31],"num":[]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     34,
  //     '"Par voie sanguine ? "',
  //     30,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[30],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     '{"if":[[{"val":"yes","var":31},{"val":"yes","var":37}]],"then":"no"}',
  //     0,
  //   ],
  //   [
  //     35,
  //     '"EPI (Gants, blouses, lunettes)"',
  //     34,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[34],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     36,
  //     '"Protocole"',
  //     34,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[34],"num":[]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     37,
  //     '"Par contact ? "',
  //     30,
  //     2,
  //     null,
  //     null,
  //     '{"yes":[30],"no":[],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     '{"if":[[{"var":31,"val":"yes"},{"val":"yes","var":34}]],"then":"no"}',
  //     0,
  //   ],
  //   [
  //     38,
  //     '"EPI"',
  //     37,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[37],"num":[]}',
  //     '["yes","no"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     39,
  //     '"Protocole"',
  //     37,
  //     1,
  //     null,
  //     null,
  //     '{"yes":[37],"num":[]}',
  //     '["ok","not_ok"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ],
  //   [
  //     40,
  //     '"Autre moyen de transmission"',
  //     30,
  //     3,
  //     null,
  //     null,
  //     '{"yes":[30],"no":[31,34,37],"num":[]}',
  //     '["text"]',
  //     '[0,1]',
  //     null,
  //     0,
  //   ]
  //   // [
  //   //   40,
  //   //   '"Médicament"',
  //   //   -1,
  //   //   6,
  //   //   null,
  //   //   null,
  //   //   '{"yes":[],"num":[]}',
  //   //   '["list_meds"]',
  //   //   '[]',
  //   //   null
  //   // ]
  // ],
  // [
  //   [
  //     '"id"',
  //     '"name"',
  //     '"parent_id"',
  //     '"position"',
  //     '"comment"',
  //     '"section_title"',
  //     '"cond"',
  //     '"check"',
  //     '"color"',
  //     '"pre_check"',
  //     '"importance',
  //   ],
  //   [
  //     1,
  //     '"Intubation Difficile ? "',
  //     -1,
  //     0,
  //     null,
  //     null,
  //     '{"yes":[],"no":[],"num":[]}',
  //     '["yes","no","idk"]',
  //     '[0,1,2]',
  //     '{"if":[[{"var":"difficult_intubation","op":"est","val":"vrai"}]],"then":"yes"}',
  //     0
  //   ],
  // ],
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Intervention Urgente"',
      -1,
      0,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0,2]',
      null,
      1
    ],
    [
      2,
      '"Dossier infirmier présent"',
      -1,
      1,
      null,
      '"Infirmière de l\'unité de soin qui prépare le patient"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      3,
      '"Patient"',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["list_patient-states"]',
      '[0]',
      null,
      0
    ],
    [
      4,
      '"Le patient décline son nom"',
      -1,
      3,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      5,
      '"Le patient décline son prénom"',
      -1,
      4,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      6,
      '"Le patient décline sa date de naissance"',
      -1,
      5,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      7,
      '"Vérifier la concordance entre le dossier et le bracelet d\'identité du patient"',
      -1,
      6,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["ok","not_ok"]',
      '[0,1]',
      null,
      0
    ],
    [
      8,
      '"Consentement du patient"',
      -1,
      7,
      '"Pdf du Consentement"',
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":17}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      9,
      '"Consentement des parents ( <18 ans )"',
      -1,
      8,
      '"Pdf du Consentement"',
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":"<","val":18}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      10,
      '"Le patient décline le côté à opérer"',
      -1,
      9,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["left","right","bilateral","idk","na"]',
      '[2,2,2,1,2]',
      null,
      0
    ],
    [
      11,
      '"L\'infirmière vérifie dans le dossier le type d\'intervention"',
      -1,
      10,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      12,
      '"Maladies transmissibles connues"',
      -1,
      11,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      13,
      '"Lesquelles ?_Maladies"',
      12,
      0,
      null,
      null,
      '{"yes":[12],"no":[],"num":[]}',
      '["list_diseases"]',
      '[1]',
      null,
      0
    ],
    [
      14,
      '"Patient(e) à jeun"',
      -1,
      12,
      null,
      '"À vérifier"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      15,
      '"Vernis à ongles ôté"',
      -1,
      13,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      16,
      '"A uriné"',
      -1,
      14,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      17,
      '"Proth. dentaire/auditives/lentilles ôtées"',
      -1,
      15,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      18,
      '"Bijoux/piercings ôtés"',
      -1,
      16,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      19,
      '"Médicamenteuses déclarées"',
      -1,
      17,
      null,
      '"Le patient déclare ses allergies"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      20,
      '"Lesquelles ?_Allergies_Meds"',
      19,
      0,
      null,
      null,
      '{"yes":[19],"no":[],"num":[]}',
      '["list_alergy-meds"]',
      '[1]',
      null,
      0
    ],
    [
      21,
      '"Alimentaires déclarées"',
      -1,
      18,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      22,
      '"Lesquelles ?_Allergies_Alim"',
      21,
      0,
      null,
      null,
      '{"yes":[21],"no":[],"num":[]}',
      '["list_alergy-aliments"]',
      '[1]',
      null,
      0
    ],
    [
      23,
      '"Hygiène du patient correcte"',
      -1,
      19,
      null,
      '"Hygiène"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      24,
      '"Propreté et intégrité du site opératoire"',
      -1,
      20,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      25,
      '"Dépilation"',
      -1,
      21,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      26,
      '"Présence de bas de contention"',
      -1,
      22,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      27,
      '"Scan :"',
      -1,
      23,
      null,
      '"Infirmièr(e) de l\'US qui a préparé le patient pour le BO "',
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0]',
      null,
      0
    ]
  ],
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Intervention Urgente"',
      -1,
      0,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0,2]',
      null,
      1
    ],
    [
      2,
      '"Dossier infirmier présent"',
      -1,
      1,
      null,
      '"Infirmière BO qui accueille le patient"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      3,
      '"Patient"',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["list_patient-states"]',
      '[0,1,1,1,1]',
      null,
      0
    ],
    [
      4,
      '"Le patient décline son nom"',
      -1,
      3,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      5,
      '"Le patient décline son prénom"',
      -1,
      4,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      6,
      '"Le patient décline sa date de naissance"',
      -1,
      5,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      7,
      '"Vérifier la concordance entre le dossier et le bracelet d\'identité du patient"',
      -1,
      6,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["ok","not_ok"]',
      '[0,1]',
      null,
      0
    ],
    [
      8,
      '"Consentement du patient"',
      -1,
      7,
      '"Pdf du Consentement"',
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":17}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      9,
      '"Consentement du parent ( <18 ans )"',
      -1,
      8,
      '"Pdf du Consentement"',
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":"<","val":18}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      10,
      '"Le patient décline le côté à opérer"',
      -1,
      9,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["left","right", "idk", "na"]',
      '[2,2,1,2]',
      null,
      0
    ],
    [
      11,
      '"L\'infirmière vérifie dans le dossier le type d\'intervention"',
      -1,
      10,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["ok", "not_ok"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      12,
      '"Maladies transmissibles connues"',
      -1,
      11,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0]',
      null,
      0
    ],
    [
      13,
      '"Lesquelles ?_Maladies"',
      12,
      0,
      null,
      null,
      '{"yes":[12],"no":[],"num":[]}',
      '["list_diseases"]',
      '[1]',
      null,
      0
    ],
    [
      14,
      '"Patient(e) à jeun"',
      -1,
      12,
      null,
      '"À vérifier"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      15,
      '"Vernis à ongles ôté"',
      -1,
      13,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      16,
      '"A uriné"',
      -1,
      14,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      17,
      '"Proth. dentaire/auditives/lentilles ôtées"',
      -1,
      15,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      18,
      '"Bijoux/piercings ôtés"',
      -1,
      16,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      19,
      '"Médicamenteuses déclarées"',
      -1,
      17,
      null,
      '"Le patient déclare ses allergies :"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      20,
      '"Lesquelles ?_Allergies_Meds"',
      19,
      0,
      null,
      null,
      '{"yes":[19],"no":[],"num":[]}',
      '["list_alergy-meds"]',
      '[1]',
      null,
      0
    ],
    [
      21,
      '"Alimentaires déclarées"',
      -1,
      18,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      22,
      '"Lesquelles ?_Allergies_Alim"',
      21,
      0,
      null,
      null,
      '{"yes":[21],"no":[],"num":[]}',
      '["list_alergy-aliments"]',
      '[1]',
      null,
      0
    ],
    [
      23,
      '"Hygiène du patient correcte"',
      -1,
      19,
      null,
      '"Hygiène"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      24,
      '"Propreté et intégrité du site opératoire"',
      -1,
      20,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      25,
      '"Dépilation"',
      -1,
      21,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      26,
      '"Présence de bas de contention"',
      -1,
      22,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"age","op":">","val":11}]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      27,
      '"Scan :"',
      -1,
      23,
      null,
      '"Infirmière qui accueille le patient au BO :"',
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0]',
      null,
      0
    ]
  ],
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Date de l\'intervention"',
      -1,
      0,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["date"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      2,
      '"Heure"',
      -1,
      1,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["hour"]',
      '[0,1]',
      null,
      0
    ],
    [
      3,
      '"Salle "',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["list_room"]',
      '[0,1]',
      null,
      0
    ],
    [
      4,
      '"Présentation des personnes inhabituelles"',
      -1,
      3,
      null,
      '"Chirurgien / Inf. circul. / Instrumentaliste / Anesthésiste"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      5,
      '"Vérification identité du patient"',
      -1,
      4,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      6,
      '"Rappel de l\'intitulé de l\'intervention"',
      -1,
      5,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      7,
      '"Site opératoire"',
      -1,
      6,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["left","right","bilateral","idk","na"]',
      '[2,2,2,1,2]',
      null,
      0
    ],
    [
      8,
      '"Maladies transmissibles"',
      -1,
      7,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0]',
      null,
      0
    ],
    [
      9,
      '"Lesquelles ?_Maladies"',
      8,
      0,
      null,
      null,
      '{"yes":[8],"no":[],"num":[]}',
      '["list_diseases"]',
      '[1]',
      null,
      0
    ],
    [
      10,
      '"Risque de perte sanguine..."',
      -1,
      8,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      11,
      '"Poches de sang..."',
      10,
      0,
      null,
      null,
      '{"yes":[10],"no":[],"num":[]}',
      '["number"]',
      '[1]',
      null,
      0
    ],
    [
      12,
      '"Cell saver disponible"',
      10,
      1,
      null,
      null,
      '{"yes":[10],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      13,
      '"Cell saver en ordre de marche"',
      10,
      2,
      null,
      null,
      '{"yes":[10],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      14,
      '"AB Prophyl."',
      -1,
      9,
      null,
      '"Vérifications administration"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[2,2]',
      null,
      0
    ],
    [
      15,
      '"Lesquels ?_Antibotiques"',
      14,
      0,
      null,
      null,
      '{"yes":[14],"no":[],"num":[]}',
      '["list_antibiotics"]',
      '[0]',
      null,
      0
    ],
    [
      16,
      '"Type d\'anésthésie "',
      -1,
      10,
      null,
      '"Anésthesiste"',
      '{"yes":[],"no":[],"num":[]}',
      '["list_anesthesia"]',
      '[0,1]',
      null,
      0
    ],
    [
      17,
      '"Matériel d\'anesthésie disponible / ordre de marche"',
      -1,
      11,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      18,
      '"Respirateur"',
      -1,
      12,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      19,
      '"Oxym. de pouls"',
      -1,
      13,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      20,
      '"Monitoring"',
      -1,
      14,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      21,
      '"Matériel de monitorage invasif disponible (cathé artériel, VVC,…) "',
      -1,
      15,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      22,
      '"Difficultés airways et/ou intubation"',
      -1,
      16,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      23,
      '"Laryngoscope"',
      22,
      0,
      null,
      null,
      '{"yes":[22],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      24,
      '"Glydescope ou équivalent présent"',
      22,
      1,
      null,
      null,
      '{"yes":[22],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      25,
      '"2ème anésthésiste"',
      22,
      2,
      null,
      null,
      '{"yes":[22],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      26,
      '"Matériel pour l\'infirmière circulante disponible et en ordre de marche "',
      -1,
      17,
      null,
      '"Infirmière circulante"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      27,
      '"Imagerie disponible "',
      -1,
      18,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      28,
      '"Matériel implantable disponible et correct "',
      -1,
      19,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      29,
      '"La stérilité du matériel disposable et non disposable a été vérifiée (résultats des indicateurs + vérification date péremption)"',
      -1,
      20,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
  ],
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Date de l\'intervention"',
      -1,
      0,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["date"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      2,
      '"Heure"',
      -1,
      1,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["hour"]',
      '[0,1]',
      null,
      0
    ],
    [
      3,
      '"Salle "',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["list_room"]',
      '[0,1]',
      null,
      0
    ],
    [
      4,
      '"Présentation des personnes inhabituelles"',
      -1,
      3,
      null,
      '"Chirurgien / Inf. circul. / Instrumentaliste / Anesthésiste"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      5,
      '"Vérification identité du patient"',
      -1,
      4,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      6,
      '"Rappel de l\'intitulé de l\'intervention"',
      -1,
      5,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
    [
      7,
      '"Site opératoire"',
      -1,
      6,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["left","right","bilateral","na"]',
      '[2,2,2,2,2]',
      null,
      0
    ],
    [
      8,
      '"Maladies transmissibles"',
      -1,
      7,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[1,0]',
      null,
      0
    ],
    [
      9,
      '"Lesquelles ?_"',
      8,
      0,
      null,
      null,
      '{"yes":[8],"no":[],"num":[]}',
      '["list_diseases"]',
      '[1]',
      null,
      0
    ],
    [
      10,
      '"Risque de perte sanguine..."',
      -1,
      8,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      11,
      '"Poches de sang..."',
      10,
      0,
      null,
      null,
      '{"yes":[10],"no":[],"num":[]}',
      '["number"]',
      '[1]',
      null,
      0
    ],
    [
      12,
      '"Vérification installation patient correcte"',
      -1,
      9,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      13,
      '"Vérification plaque bistouri"',
      -1,
      10,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      14,
      '"Vérification position patient"',
      -1,
      11,
      null,
      null,
      '{"yes":[],"no":[],"num":[{"var":"type","op":"=","val":"major"}]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      15,
      '"Documents nécessaires disponibles (RX, Imagerie, CD, ..)"',
      -1,
      12,
      null,
      '"Chirurgien"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      16,
      '"Particularité de l\'intervention liée à la chirurgie énoncée"',
      -1,
      13,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      17,
      '"Matériel pour le chirurgien et/ou l\'instrumentiste disponible"',
      -1,
      14,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      18,
      '"Vérif. compte initial des compresses"',
      -1,
      15,
      null,
      '"Anésthesiste"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no"]',
      '[0,1]',
      null,
      0
    ],
  ],
  [], // Compte des compresses
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Prélévements"',
      -1,
      0,
      null,
      '"Confirmation orale par le personnel auprès de l\'équipe"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      2,
      '"Etiquetés correctement"',
      1,
      0,
      null,
      null,
      '{"yes":[1],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      3,
      '"Acheminés correctement"',
      1,
      1,
      null,
      null,
      '{"yes":[1],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      4,
      '"Signature"',
      -1,
      1,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[0,1]',
      null,
      0
    ],
    [
      5,
      '"Signalement/notification écrite des dysfonctionnements matériels majeurs au responsable BO présent"',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[0,1,2]',
      null,
      0
    ],
    [
      6,
      '"Dysfonctionnement/ Disponibilité du matériel implantable (Vis, prothèse, greffe, ...)"',
      -1,
      3,
      null,
      '"Chirurgien / Inf. circul. / Instrumentaliste / Anesthésiste"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no","na"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      7,
      '"Drains, sonde urinaire, tamponnement, méchage, traitements, ..."',
      -1,
      4,
      null,
      '"Les prescriptions pour les suites opératoires sont vérfiées de manière conjointe (post op)"',
      '{"yes":[],"no":[],"num":[]}',
      '["yes","no", "na"]',
      '[0,1,2]',
      null,
      0
    ],
  ],
  [
    [
      '"id"',
      '"name"',
      '"parent_id"',
      '"position"',
      '"comment"',
      '"section_title"',
      '"cond"',
      '"check"',
      '"color"',
      '"pre_check"',
      '"importance'
    ],
    [
      1,
      '"Anesthésiste : Scan"',
      -1,
      0,
      null,
      '"Anesthésistes"',
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0,1]',
      null,
      0
    ],
    [
      2,
      '"Signature"',
      -1,
      1,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[0,1]',
      null,
      0
    ],
    [
      3,
      '"Assistant Anesthésiste : Scan"',
      -1,
      2,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0,1]',
      null,
      0
    ],
    [
      4,
      '"Signature"',
      -1,
      3,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[0,1]',
      null,
      0
    ],
    [
      5,
      '"Chirurgien : Scan"',
      -1,
      4,
      null,
      '"Chirurgiens"',
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0,1]',
      null,
      0
    ],
    [
      6,
      '"Signature"',
      -1,
      5,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[0,1]',
      null,
      0
    ],
    [
      7,
      '"Assistant Chirurgien : Scan"',
      -1,
      6,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0,1]',
      null,
      0
    ],
    [
      8,
      '"Signature"',
      -1,
      7,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[1,0,2]',
      null,
      0
    ],
    [
      9,
      '"Infirmière Circulante: Scan"',
      -1,
      8,
      null,
      '"Infirmières"',
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0]',
      null,
      0
    ],
    [
      10,
      '"Signature"',
      -1,
      9,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["signature"]',
      '[0]',
      null,
      0
    ],
    [
      11,
      '"Infirmière Instrumentiste : Scan"',
      -1,
      10,
      null,
      null,
      '{"yes":[],"no":[],"num":[]}',
      '["scan"]',
      '[0]',
      null,
      0
    ],
    [
      12,
      '"Signature"',
      -1,
      11,
      null,
      null,
      '{"yes":[0],"no":[],"num":[]}',
      '["signature"]',
      '[0]',
      null,
      0
    ],
  ]
]

const checklist_list = [
  {
    patient_id:"http://fr.wikipedia.org/",
    patient : {"id": 0, "lastname": "Dubois", "firstname": "Germaine", "gender": "F", "dateofbirth": "02/11/1940",
      "diabetic":"faux", "difficult_intubation":"vrai", "photo": temp_photos.photo_1, "consent_pdf":temp_photos.pdf_1,
      "type":"major", "intervention_name":"PTG"},
    checklists: [
      {checklist_id: 1, name: "Unité de soin", person: "Inf. de l'US qui prépare le patient ", type: "Chirurgie Majeure", fill: false, counter:false},
      {checklist_id: 2, name: "Accueil Patient BO", person: "Inf. BO qui accueille le patient", type: "Chirurgie Majeure", fill: false, counter:false },
      {checklist_id: 3, name: "Avant Induction Anésthésique", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anést.", type: "Chirurgie Majeure", fill: false , counter:false},
      {checklist_id: 4, name: "Avant Incision chirurgicale", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Majeure", fill: false, counter:false },
      {checklist_id: 5, name: "Compte des compresses", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Majeure", fill: false, counter:true },
      {checklist_id: 6, name: "Avant la sortie de la salle d'opération", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Majeure", fill: false, counter:false },
      {checklist_id: 7, name: "Signatures", person: "Chirurgiens/Anésthésistes/Infirmières", type: "Chirurgie Majeure", fill: false, counter:false },
  ]},
  {
    patient_id:"Hello :)",
    patient : {"id": 1, "lastname": "Vandamme", "firstname": "Gilbert", "gender": "M", "dateofbirth": "08/25/2018",
      "diabetic":"vrai", "difficult_intubation":"vrai", photo: temp_photos.photo_2, "consent_pdf":temp_photos.pdf_1,
      "type":"minor", "intervention_name":"Ablation Végétations"},
    checklists: [
      {checklist_id: 1, name: "Unité de soin", person: "Inf. de l'US qui prépare le patient ", type: "Chirurgie Mineure", fill: true, counter:false },
      {checklist_id: 2, name: "Accueil Patient BO", person: "Inf. BO qui accueille le patient", type: "Chirurgie Mineure", fill: true, counter:false },
      {checklist_id: 3, name: "Avant Induction Anésthésique", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anést.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 4, name: "Avant Incision chirurgicale", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 5, name: "Compte des compresses", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:true },
      {checklist_id: 6, name: "Avant la sortie de la salle d'opération", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 7, name: "Signatures", person: "Chirurgiens/Anésthésistes/Infirmières", type: "Chirurgie Majeure", fill: false, counter:false },

    ]},
  {
    patient_id:"http://en.m.wikipedia.org",
    patient : {"id": 2, "lastname": "Franklin", "firstname": "Rachel", "gender": "F", "dateofbirth": "08/25/1980",
      "diabetic":"faux", "difficult_intubation":"faux", photo: temp_photos.photo_3, "consent_pdf":temp_photos.pdf_1,
      "type":"minor", "intervention_name":"Varice"},
    checklists: [
      {checklist_id: 1, name: "Unité de soin", person: "Inf. de l'US qui prépare le patient ", type: "Chirurgie Mineure", fill: true, counter:false },
      {checklist_id: 2, name: "Accueil Patient BO", person: "Inf. BO qui accueille le patient", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 3, name: "Avant Induction Anésthésique", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anést.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 4, name: "Avant Incision chirurgicale", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 5, name: "Compte des compresses", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:true },
      {checklist_id: 6, name: "Avant la sortie de la salle d'opération", person: "Chirurgien/Inf. \n Circul./Instrumentiste/Anest.", type: "Chirurgie Mineure", fill: false, counter:false },
      {checklist_id: 7, name: "Signatures", person: "Chirurgiens/Anésthésistes/Infirmières", type: "Chirurgie Majeure", fill: false, counter:false },
    ]}
]


/*List of all patients*/
const patients = [
  {"id": 0, "patient_code":"http://fr.wikipedia.org/", "lastname": "Dubois", "firstname": "Germaine", "gender": "F", "dateofbirth": "02/11/1940",
    "diabetic":"faux", "difficult_intubation":"vrai", "photo": temp_photos.photo_1, "consent_pdf":temp_photos.pdf_1,
    "type":"major", "intervention_name":"PTG"},
  {"id": 1, "patient_code":"Hello :)", "lastname": "Vandamme", "firstname": "Gilbert", "gender": "M", "dateofbirth": "08/25/2018",
    "diabetic":"vrai", "difficult_intubation":"vrai", photo: temp_photos.photo_2, "consent_pdf":temp_photos.pdf_1,
    "type":"minor", "intervention_name":"Ablation Végétations"},
  {"id": 2, "patient_code":"http://en.m.wikipedia.org", "lastname": "Franklin", "firstname": "Rachel", "gender": "F", "dateofbirth": "08/25/1980",
    "diabetic":"faux", "difficult_intubation":"faux", photo: temp_photos.photo_3, "consent_pdf":temp_photos.pdf_1,
    "type":"minor", "intervention_name":"Varice"},
]

const lists = {
  "meds": ["Mc","Lis","Kl","Eft", "Aucun"],
  "diseases": ["Hépatite A", "Hépatite B", "Hépatite C","Covid", "HIV", "Tuberculose", "MRSA", ],
  "patient-states" : ["Conscient","Inconscient","Dément", "Dyscommunicant"],
  "alergy-meds" : ["Latex","Peniciline","Insuline", "Ibuprofène", ],
  "alergy-aliments" : ["Gluten","Lactose","Arachides", "Banane", "Kiwi", "Noix", "Fruits secs" ],
  "nurses" : ["Avril Charpentier"," Emilie Lachance","Camille Dupond", "Alix Lefurgey", "Bastien Bellerose", "Jérémy Duchamps",],
  "anesthesists": ["Jean Dupond", "Carole Marchal", "Louis Libier", "Charles Van Acker"],
  "room" : ["N1","N2","N3","N4","N5","N6","U1","U2","U3","U4","U5","U6","U7","U8","U9","U10","I1","I2","I3","I4"],
  "antibiotics" : ["Cefazoline","Zinacef","Flagyl"],
  "anesthesia" : ["AG", "AG + épidurale", "épidurale" , "rachi", "bloc" ]
}

const lists_trad = {"meds":"Médicaments", "diseases":"Maladies", "patient-states":"Etats Patients",
  "alergy-meds":"Allergies Médicamenteuses", "alergy-aliments":"Allergies Alimentaires", "nurses": "Infirmières",
  "anesthesists": "Anesthésistes", "room": "Salle", "antibiotics": "Antibiotiques"}

const alerts = [
]

export {checklist_trees, checklist_arrays, checklist_list, patients, lists, lists_trad, alerts}